### ISSUE TITLE
Set up useContext

### ISSUE THREAD

**Issue by John-Moore-UOA** [UoaWDCC/volunteers#128]
https://github.com/UoaWDCC/VPS/tree/master/frontend/src/context

EventContext follows SenarioContext

```[tasklist]
### Tasks
- [ ] https://github.com/UoaWDCC/volunteers/issues/130
- [ ] https://github.com/UoaWDCC/volunteers/issues/131
- [ ] https://github.com/UoaWDCC/volunteers/issues/138
```
