### ISSUE TITLE
Fix Styles

### ISSUE THREAD

**Issue by John-Moore-UOA** [UoaWDCC/volunteers#80]
### General tasks:
* Set main style background to white (not for individual tickets)
* Make all images non draggable

### Tasks for each React Component:
* Follow style document to consolidate font size, text colour, line-height, letter-spacing --> This is doable through setting the `text-` attribute inside `className`, e.g. `className="text-heading"`
* Set fonts using `className="font-sans"` or `font-serif` or `font-mono`
* Set colours using `primary`, `secondary`,`neutral` etc. Do not explicitly define these types again
* See the file at `.web\src\components\TestComponent.tsx` for examples. Its routed to `/testing` if you want to have a look.  #73 is also done in Tailwind if you'd like an example
* Use the [Tailwind docs](https://tailwindcss.com/docs/installation) to convert things like margin,, padding, align-items, etc. 
* If there's a repeating style you want to add, you can add it to the `tailwind.config.js` file 
* Note that the default style is the Main Page style. If you are doing the dashboard, add `className="dashboard"` to your outer `<div>` element 

### Acceptance Criteria:
- [ ] Original CSS file for React component is deleted (no more * or element or class selectors)
- [ ] Uses thematic names (like `bg-primary`, `text-body` etc. when available. you can still define your own custom to match the Figma)
- [ ] Styles still work 
- [ ] If you are working on the [Dashboard], make sure you have `className="Dashboard"` on your outer div

### Definition of Done:
- [ ] AC met
- [ ] Applicable tests written
- [ ] Applicable documentation is written in GH wiki
- [ ] PR reviewed
- [ ] Merged into main/feature branch

### Notes / Links
Ask daniella for values
```[tasklist]
### Tasks
- [ ] https://github.com/UoaWDCC/volunteers/issues/95
- [ ] https://github.com/UoaWDCC/volunteers/issues/97
- [ ] https://github.com/UoaWDCC/volunteers/issues/98
- [ ] https://github.com/UoaWDCC/volunteers/issues/99
- [ ] https://github.com/UoaWDCC/volunteers/issues/100
- [ ] https://github.com/UoaWDCC/volunteers/issues/101
- [ ] https://github.com/UoaWDCC/volunteers/issues/102
- [ ] https://github.com/UoaWDCC/volunteers/issues/103
- [ ] https://github.com/UoaWDCC/volunteers/issues/104
- [ ] https://github.com/UoaWDCC/volunteers/issues/112
- [ ] https://github.com/UoaWDCC/volunteers/issues/111
- [ ] https://github.com/UoaWDCC/volunteers/issues/110
- [ ] https://github.com/UoaWDCC/volunteers/issues/109
- [ ] https://github.com/UoaWDCC/volunteers/issues/107
- [ ] https://github.com/UoaWDCC/volunteers/issues/108
- [ ] https://github.com/UoaWDCC/volunteers/issues/106
```
